import type { GalleryApp } from '@/types';

export const mockApps: GalleryApp[] = [
  {
    id: 'mock-1',
    name: 'Bouncing Balls Physics',
    description: 'A colorful physics simulation with bouncing balls',
    prompt: 'Create a colorful physics simulation with bouncing balls',
    category: 'physics',
    model_a: 'deepseek/deepseek-v3.2',
    model_b: 'zai-org/glm-4.7',
    html_content_a: null,
    html_content_b: null,
    preview_video_url: null,
    is_public: true,
    like_count: 42,
    view_count: 156,
    user_id: 'mock-user-1',
    user_email: 'demo@example.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    isLiked: false,
  },
  {
    id: 'mock-2',
    name: 'Particle System',
    description: 'Beautiful particle effects generator',
    prompt: 'Create a beautiful particle effects generator',
    category: 'visual',
    model_a: 'deepseek/deepseek-v3.2',
    model_b: 'zai-org/glm-4.7',
    html_content_a: null,
    html_content_b: null,
    preview_video_url: null,
    is_public: true,
    like_count: 38,
    view_count: 120,
    user_id: 'mock-user-2',
    user_email: 'artist@example.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    isLiked: false,
  },
  {
    id: 'mock-3',
    name: 'Snake Game',
    description: 'Classic snake game with modern graphics',
    prompt: 'Create a classic snake game with modern graphics',
    category: 'game',
    model_a: 'deepseek/deepseek-v3.2',
    model_b: 'zai-org/glm-4.7',
    html_content_a: null,
    html_content_b: null,
    preview_video_url: null,
    is_public: true,
    like_count: 65,
    view_count: 230,
    user_id: 'mock-user-3',
    user_email: 'gamer@example.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    isLiked: false,
  },
  {
    id: 'mock-4',
    name: 'Gravity Simulation',
    description: 'Simulate planetary gravity interactions',
    prompt: 'Create a gravity simulation with planetary interactions',
    category: 'physics',
    model_a: 'deepseek/deepseek-v3.2',
    model_b: 'zai-org/glm-4.7',
    html_content_a: null,
    html_content_b: null,
    preview_video_url: null,
    is_public: true,
    like_count: 28,
    view_count: 89,
    user_id: 'mock-user-1',
    user_email: 'demo@example.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    isLiked: false,
  },
];

export function isMockMode(): boolean {
  return process.env.NEXT_PUBLIC_MOCK_DATA === 'true';
}

// Mock user for dev mode - always "logged in"
export const mockUser = {
  id: 'dev-user-001',
  email: 'dev@localhost',
  username: 'DevUser',
};